import { getStorage, STORAGE_KEYS } from './storage';
import type { Project, ReframeItem, RecastItem, FeedbackRecord } from '@/stores/types';

export function generateChecklist(project: Project | null): string {
  if (!project) return '';
  const decompositions = getStorage<ReframeItem[]>(STORAGE_KEYS.REFRAME_LIST, [])
    .filter((d) => d.project_id === project.id && d.status === 'done');
  const recasts = getStorage<RecastItem[]>(STORAGE_KEYS.RECAST_LIST, [])
    .filter((o) => o.project_id === project.id);
  const feedbacks = getStorage<FeedbackRecord[]>(STORAGE_KEYS.FEEDBACK_HISTORY, [])
    .filter((f) => f.project_id === project.id);

  const lines: string[] = [];
  const actorLabels: Record<string, string> = { ai: '🤖', human: '🧠', both: '🤝' };

  lines.push(`# 실행 체크리스트: ${project.name}`);
  lines.push(`> ${new Date().toLocaleDateString('ko-KR')} 생성`);
  lines.push('');

  // Core question
  if (decompositions.length > 0) {
    const latest = decompositions[decompositions.length - 1];
    if (latest.analysis) {
      lines.push(`## 핵심 질문`);
      lines.push(`**${latest.selected_question || latest.analysis.surface_task}**`);
      lines.push('');
    }
  }

  // Assumption validation checkpoint
  if (recasts.length > 0) {
    const latest = recasts[recasts.length - 1];
    if (latest.analysis?.key_assumptions && latest.analysis.key_assumptions.length > 0) {
      lines.push(`## 가정 검증 체크포인트`);
      lines.push('');
      for (const ka of latest.analysis.key_assumptions) {
        lines.push(`- [ ] **핵심 가정**: ${ka.assumption} (확신도: ${ka.certainty === 'high' ? '높음' : ka.certainty === 'medium' ? '중간' : '낮음'})`);
        if (ka.if_wrong) lines.push(`  - 틀리면: ${ka.if_wrong}`);
      }
      lines.push('');
    }
  }

  // Steps as checklist
  if (recasts.length > 0) {
    const latest = recasts[recasts.length - 1];
    const steps = latest.steps.length > 0 ? latest.steps : latest.analysis?.steps || [];

    lines.push(`## 실행 단계`);
    lines.push('');
    steps.forEach((step, i) => {
      const actor = actorLabels[step.actor] || '';
      const time = step.estimated_time ? ` (${step.estimated_time})` : '';
      lines.push(`- [ ] **Step ${i + 1}** ${actor} ${step.task}${time}`);
      if (step.checkpoint) {
        lines.push(`  - ⚑ 체크포인트: ${step.checkpoint_reason}`);
      }
    });
    lines.push('');
  }

  // Stakeholder checklist
  if (feedbacks.length > 0) {
    const latest = feedbacks[feedbacks.length - 1];
    lines.push(`## 이해관계자 확인사항`);
    lines.push('');
    for (const result of latest.results) {
      lines.push(`### ${result.overall_reaction || '페르소나'}`);
      for (const concern of (result.concerns || [])) {
        lines.push(`- [ ] ${concern}`);
      }
      for (const q of (result.first_questions || [])) {
        lines.push(`- [ ] 예상 질문 대비: ${q}`);
      }
      for (const w of (result.wants_more || [])) {
        lines.push(`- [ ] 추가 준비: ${w}`);
      }
      lines.push('');
    }
  }

  // AI limitations reminder
  if (decompositions.length > 0) {
    const latest = decompositions[decompositions.length - 1];
    if (latest.analysis && latest.analysis.ai_limitations.length > 0) {
      lines.push(`## 직접 판단 필요 (AI 한계)`);
      latest.analysis.ai_limitations.forEach((l) => lines.push(`- [ ] ${l}`));
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by Overture*');

  return lines.join('\n');
}
